### ISSUE TITLE
Bug: Inappropriate died cases sentence

### ISSUE THREAD

**Issue by Ashu0039** [thetrulymadly/coronaclusters#27]
**Describe the bug**
The sentence when reporting no of patients died due to COVID is inappropriate if the count is 0.
"Sadly, 0 patients have died due to coronavirus in Bokaro, Jharkhand."

**To Reproduce**
1. Go to 'https://www.coronaclusters.in/jharkhand/bokaro'
2. Check the live update message block.

**Expected behavior**
Should have a better wording for this case.

**Screenshots**
<img width="1346" alt="Screenshot 2021-01-09 at 9 00 34 PM" src="https://user-images.githubusercontent.com/7317457/104095599-c443b400-52bd-11eb-8f13-73c61c4ee531.png">

**Comment by craftisan** [comment]
Hi @Ashu0039 ,
Thanks for reporting the issue and apologies for the late reply. Will fix the issue.
The platform was not being updated for a long time. We are active again and are regularly updating the platform with new information.

FYI: We have launched a new initiative to help people in need of plasma. If you or anyone you know have recovered from covid-19 recently, please register to donate plasma on this platform.
https://coronaclusters.in/plasma/donate

To request for plasma: https://coronaclusters.in/plasma/request
