### ISSUE TITLE
Incorrect counts

### ISSUE THREAD

**Issue by MrRahulpd** [thetrulymadly/coronaclusters#28]
The below content displayed talks about 100% recovery which is incorrect count of people recovered.

"944856 people are so far affected in Karnataka by novel coronavirus covid-19. 926664 out of 944856 have recovered."

**Comment by craftisan** [comment]
Hi @MrRahulpd ,
Thanks for reporting the issue and apologies for late reply.
The data has been fixed now and is regularly updated. Please check now.
