### ISSUE TITLE
Bug: Statewise help link returns 404

### ISSUE THREAD

**Issue by rashib1103** [thetrulymadly/coronaclusters#38]
**Describe the bug**
MOHFW - HELPLINE NUMBERS [by State] link returns 404 

**To Reproduce**
1.Click on help button
2.In the helpful links sections, click on link MOHFW - HELPLINE NUMBERS [by State]

**Expected behavior**
Should redirect to required link and open required page.

**Screenshots**
![image](https://user-images.githubusercontent.com/83261767/116179919-9e74da80-a707-11eb-9cc3-034c4ceb4796.png)

**Comment by craftisan** [comment]
Hi @rashib1103 ,
Thanks for reporting the issue. Will fix.

**Comment by craftisan** [comment]
Fixed
