### ISSUE TITLE
Remove number

### ISSUE THREAD

**Issue by shubhagrwl** [thetrulymadly/coronaclusters#40]
Hi,

Someone has put my Number on the Donor list, so is there any way so that I can remove my number from the donor list.
I don't want someone to call me if I can't help that person.

Regards,
Shubham Agarwal

**Comment by namanshah971** [comment]
Looking for the same feature!

**Comment by riyachopra12345** [comment]
Looking for same feature

**Comment by ajay3964** [comment]
Please remove my number I have already donated still getting call per day

Being disturb

**Comment by craftisan** [comment]
Hi @shubhagrwl and @namanshah971 ,

Feature to delete your entry from the record will be live today by the evening.

You can also leave your request number here and I will delete your entry manually.
(To see your request number kindly login on the platform with your registered phone number)
