### ISSUE TITLE
Feature: delete my number 

### ISSUE THREAD

**Issue by riyachopra12345** [thetrulymadly/coronaclusters#44]
URGENT NEED TO DELETE MY NUMBER FROM THE APP AS I HAVE ALREADY DONATED STILL GETTING CALLS . Pls include this feature asap

**Comment by ajay3964** [comment]
Please delete my number I already donated still getting 10 call per day 

Beging distrub

**Comment by craftisan** [comment]
Hi @ajay3964 and @riyachopra12345,

We have updated the platform to show only those donors who have donated more than 2 weeks ago. Our team is calling donors to ensure information integrity and to help donors get only relevant calls.

**FYI: You are eligible to donate more than once.**

Please let me know here your request number and the last date you donated plasma, and I will update the same on the platform. You can see your request number by logging in.

Regardless if you still wish to delete your number, let me know.

**Comment by aditya19812401** [comment]
Delete my number too 9643805001

**Comment by aditya19812401** [comment]
Delete number 9599444729

**Comment by ajay3964** [comment]
Please delete my number I have donated , geeting 10 or more call per day ,
it's frustrating me'
Number - 7725030649

**Comment by craftisan** [comment]
All your numbers are now hidden and won't be shown.

**Comment by ajay3964** [comment]
I have already donated
Date – 10/05/2021
Number– 7725030649
Name– Ajay patel
Please delete my number now , I am receiving call or messages again and
again, being frustrated


Thankyou
