### ISSUE TITLE
Bug: [Delete Number]

### ISSUE THREAD

**Issue by Esha1985** [thetrulymadly/coronaclusters#45]
I found that it needs 28 days since testing Covid negative that one can donate plasma. I'm only 12 days into recovery and have been getting many phone calls. It's inappropriate to create hope in the hearts of those in pain, and would like my number to be removed from there. Alternatively, you may activate it only after 28 days of recovery have been completed by anyone who registers themselves on this site.

My registered number is 9833625288 and my name is Esha Adhikari. Please delete my number ASAP. Thank you.

**Comment by craftisan** [comment]
Hi @Esha1985,
We are updating the platform everyday to fix bugs and issues like the one you mentioned. As it happens, last night we updated the list of donors to show only the ones who have completed the 28-day recovery barrier.
Additionally, members of our team are also calling up donors to verify the information that they have provided.

Rest assured, your number is not visible if the date-of-positive is less than 28 days from the current date. It will be visible only after 28 days have passed.
If you still want that your number be deleted from the portal, I'd ask you to reconsider as there is a shortage of donors. Let me know what you decide.

**Comment by iNishant** [comment]
@craftisan same issue here, can you please get my number 9790464014 removed. I am getting an overwhelming number of calls and I have already connected with enough patients (way more than I can possibly donate to).

**Comment by pradhanmantra** [comment]
I can help in deleting the numbers of people who have already donated by actually calling them, For that you will have to provide me the numbers. and not deleting numbers is creating false hope and also is time-consuming to people who are searching for it.
If you want me to help you ping me @Aj_Since_1995 twitter.

**Comment by craftisan** [comment]
> @craftisan same issue here, can you please get my number 9790464014 removed. I am getting an overwhelming number of calls and I have already connected with enough patients (way more than I can possibly donate to).

We could not find any registration by this number.

**Comment by craftisan** [comment]
> I can help in deleting the numbers of people who have already donated by actually calling them, For that you will have to provide me the numbers. and not deleting numbers is creating false hope and also is time-consuming to people who are searching for it.
> If you want me to help you ping me @Aj_Since_1995 twitter.

Thank you so much for your helping hand. Much appreciated. We have already setup a calling team to get the donors list verified.
