### ISSUE TITLE
Bug: [no donors available]

### ISSUE THREAD

**Issue by Juggs215** [thetrulymadly/coronaclusters#46]
**Describe the bug**
I am getting the message 'No donors available for your area' for each and every state I'm selecting.

**To Reproduce**
1. Login 
2. Click on 'Donors list' 
3. Enter the name of the state in which you are looking for donors 

**Expected behavior**
I would be given a comprehensive list of donors to contact.

**Screenshots**
Attached below.

**Desktop (please complete the following information):**
 - Chrome Browser 

**Smartphone (please complete the following information):**
 - Xiaomi Redmi Note 4 

**Additional context**
There is a list visible when I've not logged in. As soon as I login, it shows the error. 
![WhatsApp Image 2021-05-02 at 20 55 53](https://user-images.githubusercontent.com/83543188/116818423-da38f580-ab88-11eb-9739-e74a8942395c.jpeg)

**Comment by Juggs215** [comment]
I've added the screenshot. Please let me know if you can see it.

**Comment by craftisan** [comment]
Please check now. We have updated the view. Now you can filter out different cities with distance as well
