### ISSUE TITLE
Bug: [title]Remove contact number from plasma donation

### ISSUE THREAD

**Issue by Priyal1630** [thetrulymadly/coronaclusters#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I'm not eligible for plasma donation due to low antibody count.

**Comment by Priyal1630** [comment]
Please remove Priyal Jaggi from Plasma donation list as I have been found not eligible due to absence of COVID positive report and low antibody score for donation

**Comment by craftisan** [comment]
Done
